name: Build/Test

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup GO
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:dqlite/dev
          sudo apt install build-essential dqlite-tools libdqlite-dev libraft-dev -y
      - name: Run linters
        run: make check-static

  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup GO
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:dqlite/dev
          sudo apt install build-essential dqlite-tools libdqlite-dev libraft-dev -y
      - name: Run tests
        run: make check-unit

  build:
    name: Build binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup GO
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:dqlite/dev
          sudo apt install build-essential dqlite-tools libdqlite-dev libraft-dev -y
      - name: Build binary
        run: make build
